### ISSUE TITLE
Some minor issues in rangeanalysis.js

### ISSUE THREAD

**Issue by hujiajie** [IntelLabs/RiverTrail#36]
Recently I'm trying to understand the code in rangeanalysis.js, and I think there are several minor errors.

1.https://github.com/RiverTrail/RiverTrail/blob/bfda47f18a4f2a61285604514b8200225c1d8267/jslib/jit/compiler/rangeanalysis.js#L137

I think it should be

```javascript
type = LT;
```

2.https://github.com/RiverTrail/RiverTrail/blob/bfda47f18a4f2a61285604514b8200225c1d8267/jslib/jit/compiler/rangeanalysis.js#L537

I think the resulting range should be [ left.lb - right.ub, left.ub - right.lb ], instead of [ left.lb - right.lb, left.ub - right.ub ].

3.https://github.com/RiverTrail/RiverTrail/blob/bfda47f18a4f2a61285604514b8200225c1d8267/jslib/jit/compiler/rangeanalysis.js#L545

https://github.com/RiverTrail/RiverTrail/blob/bfda47f18a4f2a61285604514b8200225c1d8267/jslib/jit/compiler/rangeanalysis.js#L546

https://github.com/RiverTrail/RiverTrail/blob/bfda47f18a4f2a61285604514b8200225c1d8267/jslib/jit/compiler/rangeanalysis.js#L557

https://github.com/RiverTrail/RiverTrail/blob/bfda47f18a4f2a61285604514b8200225c1d8267/jslib/jit/compiler/rangeanalysis.js#L558

The third argument is the same as the second argument.

Thanks

Jiajie

**Comment by jsreeram** [comment]
Thanks for reporting these bugs!
