### ISSUE TITLE
liquid-resize demo crashes Firefox

### ISSUE THREAD

**Issue by lkuper** [IntelLabs/RiverTrail#47]
The [liquid-resize demo](http://intellabs.github.io/RiverTrail/examples/liquid-resize/resize-demo.html) consistently crashes Firefox on all the platforms I've tried (Windows 7, Windows 8, Mac, Linux), and with both the old (FF 25) and new (FF 35) versions of the extension.  I don't think this is a regression caused by the new extension, because it happens with the old one, too.  We should figure out why this is happening and fix it.

**Comment by lkuper** [comment]
Submitted a crash report: https://crash-stats.mozilla.com/report/index/40dd0fbe-4744-491a-ac10-5ffc22150126

**Comment by lkuper** [comment]
I submitted a crash report: https://crash-stats.mozilla.com/report/index/40dd0fbe-4744-491a-ac10-5ffc22150126 .  @jsreeram, do you think any useful info is to be gained from this?

**Comment by jsreeram** [comment]
I have pushed a patch that fixes this. @lkuper, please let me know if it works for you. If it doesn't, please let me know.

**Comment by lkuper** [comment]
Thanks!  Yes, this fixes the crash for me on Mac and Linux.  I'm guessing you've already tested Windows.

BTW, I noticed one of your edits to the tutorial sneaked into 65c1f4e.  I'm making a bunch of tutorial changes in another branch that I'll push soon.
