### ISSUE TITLE
no .xpi in latest release

### ISSUE THREAD

**Issue by voila** [IntelLabs/RiverTrail#57]
I cannot find any .xpi file in the latest release: https://github.com/IntelLabs/RiverTrail/releases/tag/v0.35.0
Am I missing something ? How do I install the extension ?

**Comment by lkuper** [comment]
Oops -- I somehow neglected to add it to the release.  It's there now: https://github.com/IntelLabs/RiverTrail/releases/download/v0.35.0/river-trail-for-firefox.xpi

Thanks for pointing that out!
